name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: build-htz-01
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Version & Create Gitea Release
        uses: go-semantic-release/action@v1
        with:
          custom-arguments: >
            --provider gitea 
            --provider-opt gitea_host=${{ gitea.server_url }}
            --provider-opt slug=${{ github.repository }}
            --provider-opt token=${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.semantic.outputs.version != ''
        run: |
          VERSION="v${{ steps.semantic.outputs.version }}"
          IMAGE="cr.jdbnet.co.uk/jdbnet/gostream"
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest --build-arg VERSION=$VERSION .
          docker push $IMAGE:$VERSION && docker push $IMAGE:latest